export const dynamic = "force-dynamic";

export default function PrivacyPage() {
  return (
    <main style={{ padding: 24, fontFamily: "system-ui", maxWidth: 900, margin: "0 auto" }}>
      <h1 style={{ marginBottom: 8 }}>Privacy Policy</h1>
      <p style={{ marginTop: 0, opacity: 0.8 }}>
        <b>Last updated:</b> March 2026
      </p>

      <p>
        HI5 ("we", "our", or "us") respects your privacy and is committed to protecting it. This
        Privacy Policy explains how the HI5 mobile application collects, uses, and protects
        information when you use the app.
      </p>

      <p>
        HI5 is developed and operated by <b>MIRA</b>.
      </p>

      <h2 style={{ marginTop: 22 }}>1. Information We Collect</h2>
      <p>HI5 is designed to minimize data collection. Most features operate locally on your device.</p>

      <h3 style={{ marginTop: 14 }}>Contact Information (Mode 1)</h3>
      <p>If you create a contact QR code, you may voluntarily enter:</p>
      <ul>
        <li>Name or nickname</li>
        <li>Phone number</li>
        <li>Email address</li>
        <li>Company name</li>
        <li>Social media links</li>
        <li>Profile photo (optional)</li>
      </ul>
      <p>
        This information is stored locally on your device and encoded into the QR code you generate.
        HI5 does not automatically upload contact information to our servers.
      </p>

      <h3 style={{ marginTop: 14 }}>Files Shared Through QR (Mode 2)</h3>
      <p>When using Mode 2 to share files, the app uploads the selected file to secure cloud storage.</p>
      <p>Information processed may include:</p>
      <ul>
        <li>File name</li>
        <li>File type (PDF, image, video, audio, document)</li>
        <li>File size</li>
        <li>File storage path</li>
        <li>QR identifier</li>
      </ul>
      <p>
        Files are stored using Supabase cloud storage infrastructure. The QR code contains a link
        that allows the receiver to access the file.
      </p>

      <h3 style={{ marginTop: 14 }}>Device Permissions</h3>
      <p>HI5 may request:</p>
      <ul>
        <li>
          <b>Camera</b> — used to scan QR codes
        </li>
        <li>
          <b>Storage / Media access</b> — used to pick files for Mode 2 QR generation
        </li>
      </ul>
      <p>These permissions are only used for the intended functionality and not for background tracking.</p>

      <h2 style={{ marginTop: 22 }}>2. How We Use Information</h2>
      <p>Information processed by HI5 is used only to provide app features:</p>
      <ul>
        <li>Generate QR codes</li>
        <li>Share contact information</li>
        <li>Upload and access shared files</li>
        <li>Retrieve files from secure storage when QR codes are scanned</li>
      </ul>
      <p>We do not sell, rent, or trade user data.</p>

      <h2 style={{ marginTop: 22 }}>3. Data Storage</h2>
      <p>
        HI5 uses Supabase cloud infrastructure for Mode 2 file storage. Files uploaded through the
        app may be stored until removed.
      </p>
      <p>
        Contact information created in Mode 1 remains locally on the user’s device unless the user
        shares it through a QR code.
      </p>

      <h2 style={{ marginTop: 22 }}>4. Data Sharing</h2>
      <p>
        We do not share personal information with third parties except when required to deliver app
        functionality (file storage) or when required by law.
      </p>

      <h2 style={{ marginTop: 22 }}>5. QR Code Sharing</h2>
      <p>
        QR codes generated by the app may contain contact information, text, or links to uploaded
        files. Anyone who scans the QR code may access the content.
      </p>
      <p>Users should only share QR codes with people they trust.</p>

      <h2 style={{ marginTop: 22 }}>6. Security</h2>
      <p>
        We take reasonable measures to protect information including secure storage, HTTPS
        connections, and time-limited signed file links. However, no system is completely secure.
      </p>

      <h2 style={{ marginTop: 22 }}>7. Children&apos;s Privacy</h2>
      <p>HI5 is not directed to children under the age of 13 and we do not knowingly collect their data.</p>

      <h2 style={{ marginTop: 22 }}>8. Changes to This Policy</h2>
      <p>We may update this Privacy Policy from time to time and will post the updated version on this page.</p>

      <h2 style={{ marginTop: 22 }}>9. Contact</h2>
      <p>If you have questions about this Privacy Policy, contact:</p>
      <ul>
        <li>
          <b>Developer:</b> MIRA
        </li>
        <li>
          <b>Application:</b> HI5
        </li>
        <li>
          <b>Website:</b> https://hi5qr.com
        </li>
      </ul>
    </main>
  );
}